language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - cd ShareBook
  - docker build -t sharebook-api .

script:
  - dotnet build
  - dotnet test ShareBook.Test.Unit/ShareBook.Test.Unit.csproj --filter  TestCategory!=BDD