language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - docker build -t sharebook-api ShareBook/.   